### ISSUE TITLE
Great work! Can i know if all weights and files are uploaded to HuggingFace? 

### ISSUE THREAD

**Issue by WilTay1** [thunlp/Muffin#3]
<img width="521" alt="image" src="https://github.com/thunlp/Muffin/assets/133484736/77afc5a3-f269-4727-a7b1-4281e57aae83">

**Comment by yiranyyu** [comment]
Sorry for the delay. We have now finished the uploading process, and our new model trained with RLHF-V framework is updated at [hugging face](https://huggingface.co/openbmb/RLHF-V_v0) too.
