### ISSUE TITLE
How the the DPO probs calcualted? 

### ISSUE THREAD

**Issue by findalexli** [thunlp/Muffin#5]
Under the trainer:

  ref_win_avg_logp = data_dict.pop('ref_win_avg_logp')
  ref_rej_avg_logp = data_dict.pop('ref_rej_avg_logp')
  ref_win_logp = data_dict.pop('ref_win_logp')
  ref_rej_logp = data_dict.pop('ref_rej_logp')
  ref_win_per_token_logp = data_dict.pop('ref_win_per_token_logp')
  ref_rej_per_token_logp = data_dict.pop('ref_rej_per_token_logp')

Can you please explain a bit more on how are they calculated and their differences? I wasn't sure how exactly is the difference the three type of probabilities. Any pointer to a script that generated them would be appreciated!

**Comment by yiranyyu** [comment]
Sorry for the delay. We released the [script to calculate logps](https://github.com/RLHF-V/RLHF-V/blob/11175ff5e00371972ee25b0c5949b7436454d8b1/readme.md?plain=1#L143) for reference.
